#############################################################################
# Generated by PAGE version 4.25.1
#  in conjunction with Tcl version 8.6
#  Sep 16, 2019 06:50:03 PM IST  platform: Windows NT
set vTcl(timestamp) ""


if {!$vTcl(borrow) && !$vTcl(template)} {

set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #ececec
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(active_menu_fg) #000000
}




proc vTclWindow.top42 {base} {
    global vTcl
    if {$base == ""} {
        set base .top42
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -menu "$top.m49" -background #d8d6d6 
    wm focusmodel $top passive
    wm geometry $top 600x430+650+150
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1924 1041
    wm minsize $top 120 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    wm title $top "Facial"
    vTcl:DefineAlias "$top" "Toplevel1" vTcl:Toplevel:WidgetProc "" 1
    ttk::style configure TButton -background $vTcl(actual_gui_bg)
    ttk::style configure TButton -foreground $vTcl(actual_gui_fg)
    ttk::style configure TButton -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::button $top.tBu44 \
        -command open_window -takefocus {} -text login 
    vTcl:DefineAlias "$top.tBu44" "TButton1" vTcl:WidgetProc "Toplevel1" 1
    ttk::entry $top.tEn45 \
        -font TkTextFont -textvariable Username -foreground #05040f \
        -background {} -takefocus {} -cursor ibeam 
    vTcl:DefineAlias "$top.tEn45" "TEntry1" vTcl:WidgetProc "Toplevel1" 1
    ttk::entry $top.tEn46 \
        -font {-family {Segoe UI} -size 9} -textvariable Password \
        -foreground {} -background {} -takefocus {} -cursor ibeam 
    vTcl:DefineAlias "$top.tEn46" "TEntry2" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.m49
    menu $site_3_0 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(pr,menubgcolor) -font TkMenuFont \
        -foreground $vTcl(pr,menufgcolor) -tearoff 0 
    $site_3_0 add cascade \
        -menu "$site_3_0.men51" -activebackground $vTcl(analog_color_m) \
        -activeforeground #000000 -background $vTcl(pr,menubgcolor) -font {} \
        -foreground $vTcl(pr,menufgcolor) -label AdminLogin 
    menu $site_3_0.men51 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(pr,menubgcolor) -font {-family {Segoe UI} -size 9} \
        -foreground black -tearoff 0 
    $site_3_0 add cascade \
        -menu "$site_3_0.men51" -activebackground $vTcl(analog_color_m) \
        -activeforeground #000000 -background $vTcl(pr,menubgcolor) -font {} \
        -foreground $vTcl(pr,menufgcolor) -label AdminLogin \
        -menu "$site_3_0.men53" -activebackground $vTcl(analog_color_m) \
        -activeforeground #000000 -background $vTcl(pr,menubgcolor) -font {} \
        -foreground $vTcl(pr,menufgcolor) -label {About Us} 
    menu $site_3_0.men53 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(pr,menubgcolor) -font {-family {Segoe UI} -size 9} \
        -foreground black -tearoff 0 
    $site_3_0 add cascade \
        -menu "$site_3_0.men51" -activebackground $vTcl(analog_color_m) \
        -activeforeground #000000 -background $vTcl(pr,menubgcolor) -font {} \
        -foreground $vTcl(pr,menufgcolor) -label AdminLogin \
        -menu "$site_3_0.men53" -activebackground $vTcl(analog_color_m) \
        -activeforeground #000000 -background $vTcl(pr,menubgcolor) -font {} \
        -foreground $vTcl(pr,menufgcolor) -label {About Us} \
        -menu "$site_3_0.men54" -activebackground $vTcl(analog_color_m) \
        -activeforeground #000000 -background $vTcl(pr,menubgcolor) -font {} \
        -foreground $vTcl(pr,menufgcolor) -label help 
    menu $site_3_0.men54 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(pr,menubgcolor) -font {-family {Segoe UI} -size 9} \
        -foreground black -tearoff 0 
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.tBu44 \
        -in $top -x 250 -y 180 -anchor nw -bordermode ignore 
    place $top.tEn45 \
        -in $top -x 230 -y 100 -anchor nw -bordermode ignore 
    place $top.tEn46 \
        -in $top -x 230 -y 140 -anchor nw -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top42 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

