#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 4.25.1
#  in conjunction with Tcl version 8.6
#    Sep 16, 2019 06:49:33 PM IST  platform: Windows NT
import mysql.connector
import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

def set_Tk_var():
    global Username
    Username = tk.StringVar()
    global Password
    Password = tk.StringVar()

def open_window():
   un = Username.get()
   pas =  Password.get()

    # mydb = mysql.connector.connect(host="localhost", user="root", passwd="" )
    # mycursor = mydb.cursor()
    # sql = "select * from credentials.userdata where name =  '"  + un + "' and pass = '" + pas + "'"
    # mycursor.execute(sql)


def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None




   