# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'RealAttendance.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(544, 491)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pic1 = QtWidgets.QLabel(self.centralwidget)
        self.pic1.setGeometry(QtCore.QRect(60, 130, 51, 41))
        self.pic1.setText("")
        self.pic1.setObjectName("pic1")
        self.roll1 = QtWidgets.QLabel(self.centralwidget)
        self.roll1.setGeometry(QtCore.QRect(60, 190, 47, 13))
        self.roll1.setObjectName("roll1")
        self.c1 = QtWidgets.QCheckBox(self.centralwidget)
        self.c1.setGeometry(QtCore.QRect(50, 210, 70, 17))
        self.c1.setObjectName("c1")
        self.roll2 = QtWidgets.QLabel(self.centralwidget)
        self.roll2.setGeometry(QtCore.QRect(150, 190, 47, 13))
        self.roll2.setObjectName("roll2")
        self.c2 = QtWidgets.QCheckBox(self.centralwidget)
        self.c2.setGeometry(QtCore.QRect(140, 210, 70, 17))
        self.c2.setObjectName("c2")
        self.pic2 = QtWidgets.QLabel(self.centralwidget)
        self.pic2.setGeometry(QtCore.QRect(150, 130, 51, 41))
        self.pic2.setText("")
        self.pic2.setObjectName("pic2")
        self.c7 = QtWidgets.QCheckBox(self.centralwidget)
        self.c7.setGeometry(QtCore.QRect(130, 390, 70, 17))
        self.c7.setObjectName("c7")
        self.pic7 = QtWidgets.QLabel(self.centralwidget)
        self.pic7.setGeometry(QtCore.QRect(130, 310, 51, 41))
        self.pic7.setText("")
        self.pic7.setObjectName("pic7")
        self.roll7 = QtWidgets.QLabel(self.centralwidget)
        self.roll7.setGeometry(QtCore.QRect(140, 370, 47, 13))
        self.roll7.setObjectName("roll7")
        self.c8 = QtWidgets.QCheckBox(self.centralwidget)
        self.c8.setGeometry(QtCore.QRect(230, 390, 70, 17))
        self.c8.setObjectName("c8")
        self.pic8 = QtWidgets.QLabel(self.centralwidget)
        self.pic8.setGeometry(QtCore.QRect(240, 310, 51, 41))
        self.pic8.setText("")
        self.pic8.setObjectName("pic8")
        self.roll8 = QtWidgets.QLabel(self.centralwidget)
        self.roll8.setGeometry(QtCore.QRect(240, 370, 47, 13))
        self.roll8.setObjectName("roll8")
        self.roll6 = QtWidgets.QLabel(self.centralwidget)
        self.roll6.setGeometry(QtCore.QRect(50, 370, 47, 13))
        self.roll6.setObjectName("roll6")
        self.pic6 = QtWidgets.QLabel(self.centralwidget)
        self.pic6.setGeometry(QtCore.QRect(50, 310, 51, 41))
        self.pic6.setText("")
        self.pic6.setObjectName("pic6")
        self.c6 = QtWidgets.QCheckBox(self.centralwidget)
        self.c6.setGeometry(QtCore.QRect(40, 390, 70, 17))
        self.c6.setObjectName("c6")
        self.roll3 = QtWidgets.QLabel(self.centralwidget)
        self.roll3.setGeometry(QtCore.QRect(250, 190, 47, 13))
        self.roll3.setObjectName("roll3")
        self.pic3 = QtWidgets.QLabel(self.centralwidget)
        self.pic3.setGeometry(QtCore.QRect(240, 130, 51, 41))
        self.pic3.setText("")
        self.pic3.setObjectName("pic3")
        self.c3 = QtWidgets.QCheckBox(self.centralwidget)
        self.c3.setGeometry(QtCore.QRect(240, 210, 70, 17))
        self.c3.setObjectName("c3")
        self.roll9 = QtWidgets.QLabel(self.centralwidget)
        self.roll9.setGeometry(QtCore.QRect(340, 370, 47, 13))
        self.roll9.setObjectName("roll9")
        self.c4 = QtWidgets.QCheckBox(self.centralwidget)
        self.c4.setGeometry(QtCore.QRect(330, 210, 70, 17))
        self.c4.setObjectName("c4")
        self.pic9 = QtWidgets.QLabel(self.centralwidget)
        self.pic9.setGeometry(QtCore.QRect(340, 310, 51, 41))
        self.pic9.setText("")
        self.pic9.setObjectName("pic9")
        self.roll4 = QtWidgets.QLabel(self.centralwidget)
        self.roll4.setGeometry(QtCore.QRect(340, 190, 47, 13))
        self.roll4.setObjectName("roll4")
        self.pic4 = QtWidgets.QLabel(self.centralwidget)
        self.pic4.setGeometry(QtCore.QRect(340, 130, 51, 41))
        self.pic4.setText("")
        self.pic4.setObjectName("pic4")
        self.c9 = QtWidgets.QCheckBox(self.centralwidget)
        self.c9.setGeometry(QtCore.QRect(330, 390, 70, 17))
        self.c9.setObjectName("c9")
        self.c5 = QtWidgets.QCheckBox(self.centralwidget)
        self.c5.setGeometry(QtCore.QRect(430, 210, 70, 17))
        self.c5.setObjectName("c5")
        self.pic10 = QtWidgets.QLabel(self.centralwidget)
        self.pic10.setGeometry(QtCore.QRect(440, 310, 51, 41))
        self.pic10.setText("")
        self.pic10.setObjectName("pic10")
        self.pic5 = QtWidgets.QLabel(self.centralwidget)
        self.pic5.setGeometry(QtCore.QRect(440, 130, 51, 41))
        self.pic5.setText("")
        self.pic5.setObjectName("pic5")
        self.roll5 = QtWidgets.QLabel(self.centralwidget)
        self.roll5.setGeometry(QtCore.QRect(440, 190, 47, 13))
        self.roll5.setObjectName("roll5")
        self.c10 = QtWidgets.QCheckBox(self.centralwidget)
        self.c10.setGeometry(QtCore.QRect(430, 390, 70, 17))
        self.c10.setObjectName("c10")
        self.roll10 = QtWidgets.QLabel(self.centralwidget)
        self.roll10.setGeometry(QtCore.QRect(440, 370, 47, 13))
        self.roll10.setObjectName("roll10")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(250, 20, 61, 81))
        self.label.setText("")
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.roll1.setText(_translate("MainWindow", "RollNum :"))
        self.c1.setText(_translate("MainWindow", "Present"))
        self.roll2.setText(_translate("MainWindow", "RollNum :"))
        self.c2.setText(_translate("MainWindow", "Present"))
        self.c7.setText(_translate("MainWindow", "Present"))
        self.roll7.setText(_translate("MainWindow", "RollNum :"))
        self.c8.setText(_translate("MainWindow", "Present"))
        self.roll8.setText(_translate("MainWindow", "RollNum :"))
        self.roll6.setText(_translate("MainWindow", "RollNum :"))
        self.c6.setText(_translate("MainWindow", "Present"))
        self.roll3.setText(_translate("MainWindow", "RollNum :"))
        self.c3.setText(_translate("MainWindow", "Present"))
        self.roll9.setText(_translate("MainWindow", "RollNum :"))
        self.c4.setText(_translate("MainWindow", "Present"))
        self.roll4.setText(_translate("MainWindow", "RollNum :"))
        self.c9.setText(_translate("MainWindow", "Present"))
        self.c5.setText(_translate("MainWindow", "Present"))
        self.roll5.setText(_translate("MainWindow", "RollNum :"))
        self.c10.setText(_translate("MainWindow", "Present"))
        self.roll10.setText(_translate("MainWindow", "RollNum :"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
